describe('Send To Participants' , () =>{
    it('Send To Participants Test', () => {

        // Verifying LogIn Page
            cy.visit("http://unifytest.julyservices.local/Unify.V2.Web/login")
            cy.get(':nth-child(4) > .input-login').should('be.visible').type('aafahad')
            cy.get(':nth-child(5) > .input-login').should('be.visible').type('123')
            cy.xpath("//button[@type='submit']").should('be.visible')
            cy.xpath("//button[@type='submit']").click()
            cy.get('.dotted-top-right-btn').click()
            cy.get('.search-fields').click()
            cy.get('.search-fields').clear()
            cy.get('.search-fields').type('notice delivery')
            cy.get('.mt-5').click()
            cy.wait(3000)
            cy.get('.w-350px > .grid > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
            cy.wait(3000)
            cy.xpath("//span[normalize-space()='Test - 008 (Annual)']").click()
        //verifying send to participants 
            cy.get(':nth-child(1) > .grid > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
            cy.wait(3000)
            cy.xpath("//span[@class='mat-option-text'][normalize-space()='Ready to Send']").click()
            cy.get('#k-grid2-checkbox4').click()
            cy.xpath("//button[@class='jds-btn btn-small outline-primary']").should('be.visible').click()
            cy.wait(2000)
            cy.get('.mat-dialog-actions > .grid > :nth-child(2) > .jds-btn').click()
            cy.get('#cdk-overlay-3').should('have.text', 'Successfully Updated.')
            cy.get(':nth-child(1) > .grid > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
            cy.wait(3000)
            cy.xpath("//span[normalize-space()='Send to Participants']").click()
        })
    })       
